/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytx_push_FFmpegUtils */

#ifndef _Included_com_ytx_push_FFmpegUtils
#define _Included_com_ytx_push_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytx_push_FFmpegUtils
 * Method:    push
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ytx_push_FFmpegUtils_push
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
